name: Nightly Build

on:
  workflow_dispatch:
  schedule:
  # NOTE - changes to the cron spec should be pushed by https://github.com/quic-yocto-ci
  # so that build notification emails will be sent out properly.
  - cron: "23 23 * * *"   # daily job - pick a random "minute"  - top of hour can be busy in github

permissions:
  checks: write
  pull-requests: write
  contents: read
  packages: read

jobs:
  build-nightly:
    uses: ./.github/workflows/build-yocto.yml