name: Weekly Build

on:
  workflow_dispatch:
    inputs:
      ignore_tags:
        description: 'Comma separated list of tags to skip'
        type: string
        required: false
        default: "qli-2.0-rc1,qli-2.0-rc2"
  schedule:
  # NOTE - changes to the cron spec should be pushed by https://github.com/quic-yocto-ci
  # so that build notification emails will be sent out properly.
  - cron: "30 11 * * 0"   # weekly job - Run at 11:30 UTC every Sunday

permissions:
  checks: write
  pull-requests: write
  contents: read
  packages: read

jobs:
  build-weekly:
    uses: ./.github/workflows/build-yocto.yml
    with:
      ignore_tags: ${{ inputs.ignore_tags || 'qli-2.0-rc1,qli-2.0-rc2' }}
